In [1]:
import pyro
import torch
from pyro import poutine
import pandas as pd
from pyro.distributions import MultivariateNormal as MVN
from pyro.distributions import HalfCauchy
from pyro.contrib.autoguide import AutoDelta
from pyro.infer import SVI, Trace_ELBO

In [2]:
data = pd.read_csv("dataset/toyset/processed_toyset.csv")
training = data.iloc[0:1000,]
time_gap = torch.tensor(training["time_gap"].values)
training.head()

timestamp   gbpjpy    gbpusd    usdjpy  time_gap
0  2019-05-01 00:00:00  4.97986  0.265659  4.713935         1
1  2019-05-01 00:01:00  4.97986  0.265659  4.713935         1
2  2019-05-01 00:02:00  4.97986  0.265659  4.713935         1
3  2019-05-01 00:03:00  4.97986  0.265659  4.713935         1
4  2019-05-01 00:04:00  4.97986  0.265659  4.713935         1

We will denote observed exchange rates as y and latent currency intrinsic values as x

In [3]:
colnames = list(training)[1:-1]
num_exchange = len(colnames)
y_mu = torch.zeros(num_exchange)

first_curr = [exchange[0:3] for exchange in colnames]
second_curr = [exchange[3:6] for exchange in colnames]
all_curr = list(set(first_curr + second_curr))
num_currency = len(all_curr)
x_mu = torch.zeros(num_currency)

meas_matrix = []
for i in range(num_exchange):
    temp_tens = torch.zeros(num_currency)
    temp_tens[all_curr.index(first_curr[i])] = 1
    temp_tens[all_curr.index(second_curr[i])] = -1
    meas_matrix.append(temp_tens)
meas_matrix = torch.cat(meas_matrix).view(num_exchange, -1)
meas_matrix

tensor([[ 1.,  0., -1.],
        [ 1., -1.,  0.],
        [ 0.,  1., -1.]])

In [4]:
data = torch.tensor(training.iloc[:,1:-1].values)
data

tensor([[4.9799, 0.2657, 4.7139],
        [4.9799, 0.2657, 4.7139],
        [4.9799, 0.2657, 4.7139],
        ...,
        [4.9802, 0.2690, 4.7109],
        [4.9801, 0.2690, 4.7109],
        [4.9802, 0.2689, 4.7110]], dtype=torch.float64)

In [26]:
def model(data):
    num_proc_L_theta = int(num_currency ** 2)
    proc_L_theta = pyro.sample("proc_prob",
                               pyro.distributions.HalfCauchy(0.1 * torch.ones(num_proc_L_theta))
                              )
    proc_L = torch.tril(proc_L_theta.view(num_currency, -1))

    num_meas_L_theta = int(num_exchange ** 2)
    meas_L_theta = pyro.sample("meas_prob",
                              pyro.distributions.HalfCauchy(0.1 * torch.ones(num_meas_L_theta)))
    meas_L = torch.tril(meas_L_theta.view(num_exchange, -1))
    
    x = torch.zeros(num_currency)
    seq_length = data.shape[0]
    for t in pyro.markov(range(seq_length)):
        x = pyro.sample("x_{}".format(t), MVN(x, scale_tril = time_gap[t]**0.5 * proc_L))
        print("Latent state")
        print(x)
        y = pyro.sample("y_{}".format(t), MVN(torch.mv(meas_matrix, x), scale_tril = meas_L), obs = data[t])
        print("Observed")
        print(data[t])
        print(y)

In [27]:
guide = AutoDelta(model)
optimizer = pyro.optim.Adam({"lr": 0.0005})
svi = SVI(model, guide, optimizer, loss=Trace_ELBO())

In [28]:
svi.step(data)

Latent state
tensor([-0.0252, -0.0372, -0.0545], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0573, -0.1321, -0.1282], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0016, -0.0909, -0.1431], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0174, -0.1645, -0.1987], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0100, -0.0716, -0.2236], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0543,  0.0013, -0.1612], requires_grad=True)
O

Latent state
tensor([-0.7249, -1.8744, -0.8793], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.7983, -2.0759, -0.8916], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.7882, -2.0413, -0.8819], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.7463, -1.9928, -0.8575], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.7930, -2.0274, -0.8984], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.7399, -1.8427, -0.8328], requires_grad=True)
O

Latent state
tensor([-0.2236, -1.0035, -0.8015], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1592, -0.9249, -0.7853], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1816, -0.9869, -0.8100], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1776, -0.9156, -0.7874], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1330, -0.8154, -0.7042], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1716, -0.9614, -0.7393], requires_grad=True)
O

Latent state
tensor([-0.0856, -0.9282, -0.8589], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0467, -0.8034, -0.8749], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0312, -0.7562, -0.8230], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0470, -0.8900, -0.8234], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0346, -0.8690, -0.8637], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1253, -0.9509, -0.8349], requires_grad=True)
O

Latent state
tensor([-0.2847, -0.8489, -0.8808], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2210, -0.6873, -0.8613], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1635, -0.6381, -0.8527], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2661, -0.7990, -0.8957], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2981, -0.9275, -0.9652], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2384, -0.7918, -0.8973], requires_grad=True)
O

Latent state
tensor([-0.1399, -0.7217, -1.0420], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1382, -0.7654, -1.0364], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1013, -0.6673, -0.9422], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0567, -0.5749, -0.8566], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0479, -0.5532, -0.8026], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0769, -0.6213, -0.7672], requires_grad=True)
O

Latent state
tensor([ 0.0284, -0.4716, -0.5635], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0308, -0.4374, -0.5616], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0374, -0.4558, -0.5163], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0306, -0.4586, -0.5011], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0609, -0.3252, -0.4357], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0719, -0.1984, -0.3985], requires_grad=True)
O

Latent state
tensor([ 0.0863,  0.4492, -0.3333], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.1328,  0.4767, -0.3187], requires_grad=True)
Observed
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([ 0.0961,  0.4549, -0.2488], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0381,  0.2991, -0.2760], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0682,  0.3426, -0.2667], requires_grad=True)
Observed
tensor([4.9799, 0.2657, 4.7140], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7140], dtype=torch.float64)
Latent state
tensor([ 0.0358,  0.3211, -0.2910], requires_grad=True)
O

tensor([0.7436, 1.6709, 0.0897], requires_grad=True)
Observed
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([0.7567, 1.7356, 0.0621], requires_grad=True)
Observed
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([0.7793, 1.7644, 0.1007], requires_grad=True)
Observed
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([0.7518, 1.7025, 0.0263], requires_grad=True)
Observed
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([ 0.7110,  1.5674, -0.0240], requires_grad=True)
Observed
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([ 0.6852,  1.5234, -0.0979], requires_grad=True)
Observed
tensor([4.9798, 0

tensor([ 1.2329,  2.4026, -0.0417], requires_grad=True)
Observed
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 1.1893,  2.2934, -0.0919], requires_grad=True)
Observed
tensor([4.9798, 0.2657, 4.7138], dtype=torch.float64)
tensor([4.9798, 0.2657, 4.7138], dtype=torch.float64)
Latent state
tensor([ 1.2013,  2.3485, -0.0330], requires_grad=True)
Observed
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
Latent state
tensor([ 1.2360,  2.3547, -0.0778], requires_grad=True)
Observed
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 1.3022,  2.4077, -0.0330], requires_grad=True)
Observed
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
Latent state
tensor([ 1.3071,  2.4308, -0.0071], requires_grad=True)
Observed
tenso

tensor([4.9800, 0.2655, 4.7142], dtype=torch.float64)
tensor([4.9800, 0.2655, 4.7142], dtype=torch.float64)
Latent state
tensor([1.1368, 2.0023, 0.1442], requires_grad=True)
Observed
tensor([4.9799, 0.2654, 4.7142], dtype=torch.float64)
tensor([4.9799, 0.2654, 4.7142], dtype=torch.float64)
Latent state
tensor([1.1622, 2.0853, 0.1489], requires_grad=True)
Observed
tensor([4.9799, 0.2654, 4.7143], dtype=torch.float64)
tensor([4.9799, 0.2654, 4.7143], dtype=torch.float64)
Latent state
tensor([1.1519, 2.0849, 0.1371], requires_grad=True)
Observed
tensor([4.9799, 0.2654, 4.7143], dtype=torch.float64)
tensor([4.9799, 0.2654, 4.7143], dtype=torch.float64)
Latent state
tensor([1.2111, 2.2027, 0.1338], requires_grad=True)
Observed
tensor([4.9799, 0.2654, 4.7142], dtype=torch.float64)
tensor([4.9799, 0.2654, 4.7142], dtype=torch.float64)
Latent state
tensor([1.1983, 2.1842, 0.1820], requires_grad=True)
Observed
tensor([4.9799, 0.2654, 4.7142], dtype=torch.float64)
tensor([4.9799, 0.2654, 4.7142]

tensor([1.3195, 2.3035, 0.0139], requires_grad=True)
Observed
tensor([4.9802, 0.2657, 4.7143], dtype=torch.float64)
tensor([4.9802, 0.2657, 4.7143], dtype=torch.float64)
Latent state
tensor([1.3086, 2.2903, 0.0029], requires_grad=True)
Observed
tensor([4.9805, 0.2661, 4.7141], dtype=torch.float64)
tensor([4.9805, 0.2661, 4.7141], dtype=torch.float64)
Latent state
tensor([1.3118, 2.2440, 0.0258], requires_grad=True)
Observed
tensor([4.9809, 0.2665, 4.7141], dtype=torch.float64)
tensor([4.9809, 0.2665, 4.7141], dtype=torch.float64)
Latent state
tensor([1.3566, 2.3182, 0.0808], requires_grad=True)
Observed
tensor([4.9808, 0.2665, 4.7141], dtype=torch.float64)
tensor([4.9808, 0.2665, 4.7141], dtype=torch.float64)
Latent state
tensor([1.3137, 2.2388, 0.0217], requires_grad=True)
Observed
tensor([4.9808, 0.2665, 4.7141], dtype=torch.float64)
tensor([4.9808, 0.2665, 4.7141], dtype=torch.float64)
Latent state
tensor([ 1.2568,  2.1086, -0.0434], requires_grad=True)
Observed
tensor([4.9808, 0.26

tensor([4.9807, 0.2667, 4.7137], dtype=torch.float64)
tensor([4.9807, 0.2667, 4.7137], dtype=torch.float64)
Latent state
tensor([1.3885, 2.5054, 0.1138], requires_grad=True)
Observed
tensor([4.9807, 0.2667, 4.7138], dtype=torch.float64)
tensor([4.9807, 0.2667, 4.7138], dtype=torch.float64)
Latent state
tensor([1.3204, 2.4027, 0.1040], requires_grad=True)
Observed
tensor([4.9806, 0.2667, 4.7136], dtype=torch.float64)
tensor([4.9806, 0.2667, 4.7136], dtype=torch.float64)
Latent state
tensor([1.4026, 2.5273, 0.1538], requires_grad=True)
Observed
tensor([4.9805, 0.2667, 4.7136], dtype=torch.float64)
tensor([4.9805, 0.2667, 4.7136], dtype=torch.float64)
Latent state
tensor([1.4122, 2.5005, 0.1351], requires_grad=True)
Observed
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
Latent state
tensor([1.3784, 2.4390, 0.0861], requires_grad=True)
Observed
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
tensor([4.9807, 0.2668, 4.7136]

tensor([1.2094, 2.0542, 0.3968], requires_grad=True)
Observed
tensor([4.9809, 0.2672, 4.7135], dtype=torch.float64)
tensor([4.9809, 0.2672, 4.7135], dtype=torch.float64)
Latent state
tensor([1.1673, 1.9150, 0.3722], requires_grad=True)
Observed
tensor([4.9810, 0.2672, 4.7135], dtype=torch.float64)
tensor([4.9810, 0.2672, 4.7135], dtype=torch.float64)
Latent state
tensor([1.1431, 1.8634, 0.3587], requires_grad=True)
Observed
tensor([4.9810, 0.2673, 4.7135], dtype=torch.float64)
tensor([4.9810, 0.2673, 4.7135], dtype=torch.float64)
Latent state
tensor([1.0879, 1.8255, 0.3900], requires_grad=True)
Observed
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
Latent state
tensor([1.1568, 1.9735, 0.4278], requires_grad=True)
Observed
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
Latent state
tensor([1.2268, 2.0390, 0.4849], requires_grad=True)
Observed
tensor([4.9813, 0.2677,

tensor([4.9809, 0.2679, 4.7128], dtype=torch.float64)
Latent state
tensor([0.7049, 0.9409, 0.1143], requires_grad=True)
Observed
tensor([4.9810, 0.2679, 4.7128], dtype=torch.float64)
tensor([4.9810, 0.2679, 4.7128], dtype=torch.float64)
Latent state
tensor([0.6431, 0.8060, 0.0707], requires_grad=True)
Observed
tensor([4.9809, 0.2679, 4.7128], dtype=torch.float64)
tensor([4.9809, 0.2679, 4.7128], dtype=torch.float64)
Latent state
tensor([0.6055, 0.7410, 0.0079], requires_grad=True)
Observed
tensor([4.9809, 0.2679, 4.7127], dtype=torch.float64)
tensor([4.9809, 0.2679, 4.7127], dtype=torch.float64)
Latent state
tensor([0.5998, 0.7687, 0.0477], requires_grad=True)
Observed
tensor([4.9806, 0.2679, 4.7125], dtype=torch.float64)
tensor([4.9806, 0.2679, 4.7125], dtype=torch.float64)
Latent state
tensor([0.6441, 0.8904, 0.1107], requires_grad=True)
Observed
tensor([4.9808, 0.2680, 4.7126], dtype=torch.float64)
tensor([4.9808, 0.2680, 4.7126], dtype=torch.float64)
Latent state
tensor([0.7136, 0.

tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
Latent state
tensor([0.6890, 1.1727, 0.2932], requires_grad=True)
Observed
tensor([4.9803, 0.2678, 4.7123], dtype=torch.float64)
tensor([4.9803, 0.2678, 4.7123], dtype=torch.float64)
Latent state
tensor([0.6909, 1.1646, 0.2366], requires_grad=True)
Observed
tensor([4.9802, 0.2676, 4.7123], dtype=torch.float64)
tensor([4.9802, 0.2676, 4.7123], dtype=torch.float64)
Latent state
tensor([0.7162, 1.2158, 0.1907], requires_grad=True)
Observed
tensor([4.9803, 0.2677, 4.7124], dtype=torch.float64)
tensor([4.9803, 0.2677, 4.7124], dtype=torch.float64)
Latent state
tensor([0.6839, 1.1477, 0.1840], requires_grad=True)
Observed
tensor([4.9803, 0.2677, 4.7123], dtype=torch.float64)
tensor([4.9803, 0.2677, 4.7123], dtype=torch.float64)
Latent state
tensor([0.7016, 1.1825, 0.1708], requires_grad=True)
Observed
tensor([4.9803, 0.2678, 4.7123], dtype=torch.float64)
tensor([4.9803, 0.2678, 4.7123]

tensor([1.0562, 1.9301, 0.3579], requires_grad=True)
Observed
tensor([4.9797, 0.2675, 4.7119], dtype=torch.float64)
tensor([4.9797, 0.2675, 4.7119], dtype=torch.float64)
Latent state
tensor([1.0783, 1.9215, 0.3736], requires_grad=True)
Observed
tensor([4.9798, 0.2676, 4.7119], dtype=torch.float64)
tensor([4.9798, 0.2676, 4.7119], dtype=torch.float64)
Latent state
tensor([1.0722, 1.9205, 0.3942], requires_grad=True)
Observed
tensor([4.9798, 0.2676, 4.7120], dtype=torch.float64)
tensor([4.9798, 0.2676, 4.7120], dtype=torch.float64)
Latent state
tensor([1.0685, 1.9411, 0.4261], requires_grad=True)
Observed
tensor([4.9799, 0.2676, 4.7120], dtype=torch.float64)
tensor([4.9799, 0.2676, 4.7120], dtype=torch.float64)
Latent state
tensor([1.0345, 1.9079, 0.4394], requires_grad=True)
Observed
tensor([4.9799, 0.2676, 4.7120], dtype=torch.float64)
tensor([4.9799, 0.2676, 4.7120], dtype=torch.float64)
Latent state
tensor([0.9894, 1.9298, 0.4549], requires_grad=True)
Observed
tensor([4.9799, 0.2676,

tensor([4.9800, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0491, 2.5206, 0.4978], requires_grad=True)
Observed
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0483, 2.5459, 0.5201], requires_grad=True)
Observed
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0185, 2.4944, 0.4926], requires_grad=True)
Observed
tensor([4.9801, 0.2674, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2674, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0296, 2.5298, 0.4285], requires_grad=True)
Observed
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.1038, 2.6421, 0.5073], requires_grad=True)
Observed
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.1295, 2.

tensor([4.9802, 0.2674, 4.7125], dtype=torch.float64)
tensor([4.9802, 0.2674, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0788, 2.7177, 0.5973], requires_grad=True)
Observed
tensor([4.9803, 0.2674, 4.7126], dtype=torch.float64)
tensor([4.9803, 0.2674, 4.7126], dtype=torch.float64)
Latent state
tensor([1.0458, 2.6919, 0.6190], requires_grad=True)
Observed
tensor([4.9803, 0.2673, 4.7127], dtype=torch.float64)
tensor([4.9803, 0.2673, 4.7127], dtype=torch.float64)
Latent state
tensor([1.1052, 2.8246, 0.6293], requires_grad=True)
Observed
tensor([4.9804, 0.2672, 4.7129], dtype=torch.float64)
tensor([4.9804, 0.2672, 4.7129], dtype=torch.float64)
Latent state
tensor([1.1236, 2.7989, 0.6375], requires_grad=True)
Observed
tensor([4.9803, 0.2672, 4.7128], dtype=torch.float64)
tensor([4.9803, 0.2672, 4.7128], dtype=torch.float64)
Latent state
tensor([1.1461, 2.8851, 0.6857], requires_grad=True)
Observed
tensor([4.9803, 0.2672, 4.7128], dtype=torch.float64)
tensor([4.9803, 0.2672, 4.7128]

tensor([1.1094, 3.0630, 1.0330], requires_grad=True)
Observed
tensor([4.9807, 0.2673, 4.7131], dtype=torch.float64)
tensor([4.9807, 0.2673, 4.7131], dtype=torch.float64)
Latent state
tensor([1.1586, 3.2286, 1.0830], requires_grad=True)
Observed
tensor([4.9805, 0.2672, 4.7130], dtype=torch.float64)
tensor([4.9805, 0.2672, 4.7130], dtype=torch.float64)
Latent state
tensor([1.1947, 3.3034, 1.0991], requires_grad=True)
Observed
tensor([4.9805, 0.2673, 4.7129], dtype=torch.float64)
tensor([4.9805, 0.2673, 4.7129], dtype=torch.float64)
Latent state
tensor([1.1849, 3.2880, 1.0641], requires_grad=True)
Observed
tensor([4.9804, 0.2672, 4.7130], dtype=torch.float64)
tensor([4.9804, 0.2672, 4.7130], dtype=torch.float64)
Latent state
tensor([1.1693, 3.1735, 1.0831], requires_grad=True)
Observed
tensor([4.9803, 0.2671, 4.7129], dtype=torch.float64)
tensor([4.9803, 0.2671, 4.7129], dtype=torch.float64)
Latent state
tensor([1.1407, 3.1514, 1.1150], requires_grad=True)
Observed
tensor([4.9805, 0.2674,

tensor([4.9807, 0.2678, 4.7126], dtype=torch.float64)
Latent state
tensor([1.7167, 4.0461, 1.1124], requires_grad=True)
Observed
tensor([4.9806, 0.2677, 4.7126], dtype=torch.float64)
tensor([4.9806, 0.2677, 4.7126], dtype=torch.float64)
Latent state
tensor([1.6056, 3.8254, 1.0572], requires_grad=True)
Observed
tensor([4.9805, 0.2677, 4.7125], dtype=torch.float64)
tensor([4.9805, 0.2677, 4.7125], dtype=torch.float64)
Latent state
tensor([1.6261, 3.8775, 1.0810], requires_grad=True)
Observed
tensor([4.9807, 0.2679, 4.7125], dtype=torch.float64)
tensor([4.9807, 0.2679, 4.7125], dtype=torch.float64)
Latent state
tensor([1.7211, 4.0216, 1.1215], requires_grad=True)
Observed
tensor([4.9807, 0.2679, 4.7126], dtype=torch.float64)
tensor([4.9807, 0.2679, 4.7126], dtype=torch.float64)
Latent state
tensor([1.6509, 3.7980, 1.0589], requires_grad=True)
Observed
tensor([4.9807, 0.2678, 4.7126], dtype=torch.float64)
tensor([4.9807, 0.2678, 4.7126], dtype=torch.float64)
Latent state
tensor([1.6359, 3.

tensor([4.9798, 0.2683, 4.7112], dtype=torch.float64)
tensor([4.9798, 0.2683, 4.7112], dtype=torch.float64)
Latent state
tensor([1.7400, 3.2252, 0.4473], requires_grad=True)
Observed
tensor([4.9796, 0.2681, 4.7112], dtype=torch.float64)
tensor([4.9796, 0.2681, 4.7112], dtype=torch.float64)
Latent state
tensor([1.7177, 3.1789, 0.4257], requires_grad=True)
Observed
tensor([4.9797, 0.2681, 4.7114], dtype=torch.float64)
tensor([4.9797, 0.2681, 4.7114], dtype=torch.float64)
Latent state
tensor([1.7464, 3.1389, 0.3450], requires_grad=True)
Observed
tensor([4.9798, 0.2681, 4.7114], dtype=torch.float64)
tensor([4.9798, 0.2681, 4.7114], dtype=torch.float64)
Latent state
tensor([1.8391, 3.3573, 0.3369], requires_grad=True)
Observed
tensor([4.9799, 0.2681, 4.7115], dtype=torch.float64)
tensor([4.9799, 0.2681, 4.7115], dtype=torch.float64)
Latent state
tensor([1.8356, 3.3535, 0.3116], requires_grad=True)
Observed
tensor([4.9798, 0.2680, 4.7116], dtype=torch.float64)
tensor([4.9798, 0.2680, 4.7116]

tensor([1.9054, 3.4047, 0.6034], requires_grad=True)
Observed
tensor([4.9806, 0.2694, 4.7109], dtype=torch.float64)
tensor([4.9806, 0.2694, 4.7109], dtype=torch.float64)
Latent state
tensor([1.8857, 3.3477, 0.5115], requires_grad=True)
Observed
tensor([4.9802, 0.2691, 4.7108], dtype=torch.float64)
tensor([4.9802, 0.2691, 4.7108], dtype=torch.float64)
Latent state
tensor([1.9506, 3.4920, 0.5201], requires_grad=True)
Observed
tensor([4.9803, 0.2690, 4.7110], dtype=torch.float64)
tensor([4.9803, 0.2690, 4.7110], dtype=torch.float64)
Latent state
tensor([1.8766, 3.3250, 0.5135], requires_grad=True)
Observed
tensor([4.9800, 0.2687, 4.7110], dtype=torch.float64)
tensor([4.9800, 0.2687, 4.7110], dtype=torch.float64)
Latent state
tensor([1.8568, 3.2620, 0.5118], requires_grad=True)
Observed
tensor([4.9803, 0.2690, 4.7110], dtype=torch.float64)
tensor([4.9803, 0.2690, 4.7110], dtype=torch.float64)
Latent state
tensor([1.8625, 3.3039, 0.5131], requires_grad=True)
Observed
tensor([4.9803, 0.2691,

tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2156, -0.2806, -0.2766], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1933, -0.2435, -0.2844], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1887, -0.3328, -0.3544], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2455, -0.4351, -0.2761], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2570, -0.4990, -0.3074], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=t

Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.4026, -1.3925, -0.8414], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3517, -1.2534, -0.7710], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3773, -1.2559, -0.7448], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.4631, -1.3728, -0.7879], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.4989, -1.4432, -0.8260], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139]

Latent state
tensor([ 0.1430, -0.6061, -0.7501], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.1655, -0.5264, -0.6758], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0970, -0.6672, -0.6696], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0180, -0.9480, -0.7613], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0258, -1.0242, -0.7543], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.0269, -1.0060, -

tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1487, -0.7738, -0.9827], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.1418, -0.7149, -1.0243], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2269, -0.8488, -1.0577], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2690, -0.9794, -1.1154], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.2181, -0.8908, -1.0726], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=t

tensor([-0.4121, -1.0596, -1.1549], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3946, -1.0245, -1.1669], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3217, -0.8250, -1.1193], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3508, -0.8435, -1.1088], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.3526, -0.8565, -1.1076], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.4648, -1.0699, -1.1959], grad

tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0290, -0.6413, -0.5821], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0501, -0.7120, -0.6071], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0126, -0.6583, -0.6005], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0199, -0.7331, -0.5960], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([-0.0844, -0.7786, -0.6396], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=t

Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.1483,  0.2543, -0.4057], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.2220,  0.4001, -0.3828], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.2333,  0.3886, -0.4190], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.3127,  0.5123, -0.3981], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9799, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.1864,  0.2895, -0.4331], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2657, 4.7139]

Latent state
tensor([ 0.1707,  0.5278, -0.2404], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.2520,  0.6947, -0.2117], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.2703,  0.6940, -0.2175], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
tensor([4.9799, 0.2656, 4.7140], dtype=torch.float64)
Latent state
tensor([ 0.2478,  0.6443, -0.2251], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.2829,  0.7134, -0.1956], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.3187,  0.7949, -

tensor([4.9796, 0.2655, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.6140,  1.4353, -0.1080], grad_fn=<ExpandBackward>)
Observed
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.6633,  1.4683, -0.1143], grad_fn=<ExpandBackward>)
Observed
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.7075,  1.6054, -0.0614], grad_fn=<ExpandBackward>)
Observed
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.7547,  1.6819, -0.0561], grad_fn=<ExpandBackward>)
Observed
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
Latent state
tensor([ 0.7626,  1.7143, -0.0102], grad_fn=<ExpandBackward>)
Observed
tensor([4.9796, 0.2654, 4.7139], dtype=torch.float64)
tensor([4.9796, 0.2654, 4.7139], dtype=t

Observed
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
Latent state
tensor([ 1.2226,  2.2048, -0.0081], grad_fn=<ExpandBackward>)
Observed
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
tensor([4.9797, 0.2657, 4.7138], dtype=torch.float64)
Latent state
tensor([1.2787, 2.2675, 0.0208], grad_fn=<ExpandBackward>)
Observed
tensor([4.9797, 0.2656, 4.7138], dtype=torch.float64)
tensor([4.9797, 0.2656, 4.7138], dtype=torch.float64)
Latent state
tensor([1.2728, 2.2703, 0.0630], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2657, 4.7139], dtype=torch.float64)
Latent state
tensor([1.3988, 2.5075, 0.1070], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
tensor([4.9798, 0.2656, 4.7139], dtype=torch.float64)
Latent state
tensor([1.3662, 2.4666, 0.0760], grad_fn=<ExpandBackward>)
Observed
tensor([4.9797, 0.2656, 4.7138], dtype=torc

tensor([4.9798, 0.2653, 4.7143], dtype=torch.float64)
Latent state
tensor([1.2539, 2.3508, 0.1455], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2653, 4.7143], dtype=torch.float64)
tensor([4.9799, 0.2653, 4.7143], dtype=torch.float64)
Latent state
tensor([1.3135, 2.4581, 0.2228], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2653, 4.7144], dtype=torch.float64)
tensor([4.9799, 0.2653, 4.7144], dtype=torch.float64)
Latent state
tensor([1.3439, 2.5425, 0.2220], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2652, 4.7143], dtype=torch.float64)
tensor([4.9798, 0.2652, 4.7143], dtype=torch.float64)
Latent state
tensor([1.3130, 2.4807, 0.1755], grad_fn=<ExpandBackward>)
Observed
tensor([4.9797, 0.2651, 4.7143], dtype=torch.float64)
tensor([4.9797, 0.2651, 4.7143], dtype=torch.float64)
Latent state
tensor([1.3071, 2.4604, 0.1812], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2653, 4.7143], dtype=torch.float64)
tensor([4.9799, 0.2653, 4.7143], dtype=torch.float64)
L

Latent state
tensor([ 1.2568,  2.1086, -0.0434], grad_fn=<ExpandBackward>)
Observed
tensor([4.9808, 0.2665, 4.7140], dtype=torch.float64)
tensor([4.9808, 0.2665, 4.7140], dtype=torch.float64)
Latent state
tensor([1.2807, 2.2127, 0.0535], grad_fn=<ExpandBackward>)
Observed
tensor([4.9808, 0.2666, 4.7140], dtype=torch.float64)
tensor([4.9808, 0.2666, 4.7140], dtype=torch.float64)
Latent state
tensor([ 1.2188,  2.1170, -0.0149], grad_fn=<ExpandBackward>)
Observed
tensor([4.9809, 0.2666, 4.7140], dtype=torch.float64)
tensor([4.9809, 0.2666, 4.7140], dtype=torch.float64)
Latent state
tensor([ 1.2149,  2.0904, -0.0371], grad_fn=<ExpandBackward>)
Observed
tensor([4.9809, 0.2666, 4.7140], dtype=torch.float64)
tensor([4.9809, 0.2666, 4.7140], dtype=torch.float64)
Latent state
tensor([ 1.1663,  2.0341, -0.0237], grad_fn=<ExpandBackward>)
Observed
tensor([4.9810, 0.2667, 4.7140], dtype=torch.float64)
tensor([4.9810, 0.2667, 4.7140], dtype=torch.float64)
Latent state
tensor([ 1.1468,  2.0282, -0.0

tensor([4.9805, 0.2667, 4.7136], dtype=torch.float64)
Latent state
tensor([1.4122, 2.5005, 0.1351], grad_fn=<ExpandBackward>)
Observed
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
Latent state
tensor([1.3784, 2.4390, 0.0861], grad_fn=<ExpandBackward>)
Observed
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
tensor([4.9807, 0.2668, 4.7136], dtype=torch.float64)
Latent state
tensor([1.3703, 2.4616, 0.0721], grad_fn=<ExpandBackward>)
Observed
tensor([4.9806, 0.2667, 4.7136], dtype=torch.float64)
tensor([4.9806, 0.2667, 4.7136], dtype=torch.float64)
Latent state
tensor([1.3484, 2.4381, 0.0326], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2666, 4.7137], dtype=torch.float64)
tensor([4.9805, 0.2666, 4.7137], dtype=torch.float64)
Latent state
tensor([1.3309, 2.3404, 0.0506], grad_fn=<ExpandBackward>)
Observed
tensor([4.9806, 0.2666, 4.7137], dtype=torch.float64)
tensor([4.9806, 0.2666, 4.7137], dtype=torch.float64)
L

Latent state
tensor([1.1431, 1.8634, 0.3587], grad_fn=<ExpandBackward>)
Observed
tensor([4.9810, 0.2673, 4.7135], dtype=torch.float64)
tensor([4.9810, 0.2673, 4.7135], dtype=torch.float64)
Latent state
tensor([1.0879, 1.8255, 0.3900], grad_fn=<ExpandBackward>)
Observed
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
Latent state
tensor([1.1568, 1.9735, 0.4278], grad_fn=<ExpandBackward>)
Observed
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
tensor([4.9812, 0.2675, 4.7135], dtype=torch.float64)
Latent state
tensor([1.2268, 2.0390, 0.4849], grad_fn=<ExpandBackward>)
Observed
tensor([4.9813, 0.2677, 4.7134], dtype=torch.float64)
tensor([4.9813, 0.2677, 4.7134], dtype=torch.float64)
Latent state
tensor([1.2018, 2.0085, 0.4697], grad_fn=<ExpandBackward>)
Observed
tensor([4.9812, 0.2676, 4.7134], dtype=torch.float64)
tensor([4.9812, 0.2676, 4.7134], dtype=torch.float64)
Latent state
tensor([1.2469, 2.1025, 0.4513], grad_fn=<

tensor([0.7049, 0.9409, 0.1143], grad_fn=<ExpandBackward>)
Observed
tensor([4.9810, 0.2679, 4.7128], dtype=torch.float64)
tensor([4.9810, 0.2679, 4.7128], dtype=torch.float64)
Latent state
tensor([0.6431, 0.8060, 0.0707], grad_fn=<ExpandBackward>)
Observed
tensor([4.9809, 0.2679, 4.7128], dtype=torch.float64)
tensor([4.9809, 0.2679, 4.7128], dtype=torch.float64)
Latent state
tensor([0.6055, 0.7410, 0.0079], grad_fn=<ExpandBackward>)
Observed
tensor([4.9809, 0.2679, 4.7127], dtype=torch.float64)
tensor([4.9809, 0.2679, 4.7127], dtype=torch.float64)
Latent state
tensor([0.5998, 0.7687, 0.0477], grad_fn=<ExpandBackward>)
Observed
tensor([4.9806, 0.2679, 4.7125], dtype=torch.float64)
tensor([4.9806, 0.2679, 4.7125], dtype=torch.float64)
Latent state
tensor([0.6441, 0.8904, 0.1107], grad_fn=<ExpandBackward>)
Observed
tensor([4.9808, 0.2680, 4.7126], dtype=torch.float64)
tensor([4.9808, 0.2680, 4.7126], dtype=torch.float64)
Latent state
tensor([0.7136, 0.9438, 0.1102], grad_fn=<ExpandBackwar

Observed
tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
Latent state
tensor([0.7077, 1.2230, 0.3615], grad_fn=<ExpandBackward>)
Observed
tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
tensor([4.9804, 0.2677, 4.7124], dtype=torch.float64)
Latent state
tensor([0.6890, 1.1727, 0.2932], grad_fn=<ExpandBackward>)
Observed
tensor([4.9803, 0.2678, 4.7123], dtype=torch.float64)
tensor([4.9803, 0.2678, 4.7123], dtype=torch.float64)
Latent state
tensor([0.6909, 1.1646, 0.2366], grad_fn=<ExpandBackward>)
Observed
tensor([4.9802, 0.2676, 4.7123], dtype=torch.float64)
tensor([4.9802, 0.2676, 4.7123], dtype=torch.float64)
Latent state
tensor([0.7162, 1.2158, 0.1907], grad_fn=<ExpandBackward>)
Observed
tensor([4.9803, 0.2677, 4.7124], dtype=torch.float64)
tensor([4.9803, 0.2677, 4.7124], dtype=torch.float64)
Latent state
tensor([0.6839, 1.1477, 0.1840], grad_fn=<ExpandBackward>)
Observed
tensor([4.9803, 0.2677, 4.7123], dtype=torch.f

tensor([4.9801, 0.2675, 4.7123], dtype=torch.float64)
Latent state
tensor([1.0966, 2.0870, 0.3961], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2675, 4.7122], dtype=torch.float64)
tensor([4.9800, 0.2675, 4.7122], dtype=torch.float64)
Latent state
tensor([1.1174, 2.0783, 0.3784], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2677, 4.7119], dtype=torch.float64)
tensor([4.9798, 0.2677, 4.7119], dtype=torch.float64)
Latent state
tensor([1.0562, 1.9301, 0.3579], grad_fn=<ExpandBackward>)
Observed
tensor([4.9797, 0.2675, 4.7119], dtype=torch.float64)
tensor([4.9797, 0.2675, 4.7119], dtype=torch.float64)
Latent state
tensor([1.0783, 1.9215, 0.3736], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2676, 4.7119], dtype=torch.float64)
tensor([4.9798, 0.2676, 4.7119], dtype=torch.float64)
Latent state
tensor([1.0722, 1.9205, 0.3942], grad_fn=<ExpandBackward>)
Observed
tensor([4.9798, 0.2676, 4.7120], dtype=torch.float64)
tensor([4.9798, 0.2676, 4.7120], dtype=torch.float64)
L

Latent state
tensor([1.0512, 2.4890, 0.5002], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2674, 4.7123], dtype=torch.float64)
tensor([4.9799, 0.2674, 4.7123], dtype=torch.float64)
Latent state
tensor([1.0342, 2.4493, 0.5164], grad_fn=<ExpandBackward>)
Observed
tensor([4.9799, 0.2674, 4.7123], dtype=torch.float64)
tensor([4.9799, 0.2674, 4.7123], dtype=torch.float64)
Latent state
tensor([1.0970, 2.6296, 0.5625], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2673, 4.7124], dtype=torch.float64)
tensor([4.9800, 0.2673, 4.7124], dtype=torch.float64)
Latent state
tensor([1.0294, 2.4787, 0.5334], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9800, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0491, 2.5206, 0.4978], grad_fn=<ExpandBackward>)
Observed
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
tensor([4.9801, 0.2673, 4.7125], dtype=torch.float64)
Latent state
tensor([1.0483, 2.5459, 0.5201], grad_fn=<

tensor([1.1514, 2.8721, 0.6783], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2679, 4.7123], dtype=torch.float64)
tensor([4.9805, 0.2679, 4.7123], dtype=torch.float64)
Latent state
tensor([1.1099, 2.8167, 0.6449], grad_fn=<ExpandBackward>)
Observed
tensor([4.9803, 0.2679, 4.7122], dtype=torch.float64)
tensor([4.9803, 0.2679, 4.7122], dtype=torch.float64)
Latent state
tensor([1.0436, 2.7484, 0.6428], grad_fn=<ExpandBackward>)
Observed
tensor([4.9803, 0.2680, 4.7121], dtype=torch.float64)
tensor([4.9803, 0.2680, 4.7121], dtype=torch.float64)
Latent state
tensor([1.0614, 2.8150, 0.6711], grad_fn=<ExpandBackward>)
Observed
tensor([4.9807, 0.2679, 4.7126], dtype=torch.float64)
tensor([4.9807, 0.2679, 4.7126], dtype=torch.float64)
Latent state
tensor([1.0156, 2.7387, 0.6398], grad_fn=<ExpandBackward>)
Observed
tensor([4.9804, 0.2675, 4.7126], dtype=torch.float64)
tensor([4.9804, 0.2675, 4.7126], dtype=torch.float64)
Latent state
tensor([0.9768, 2.6090, 0.5628], grad_fn=<ExpandBackwar

Observed
tensor([4.9805, 0.2669, 4.7133], dtype=torch.float64)
tensor([4.9805, 0.2669, 4.7133], dtype=torch.float64)
Latent state
tensor([1.1563, 2.9109, 1.0591], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2670, 4.7132], dtype=torch.float64)
tensor([4.9805, 0.2670, 4.7132], dtype=torch.float64)
Latent state
tensor([1.2508, 3.1154, 1.0613], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2671, 4.7132], dtype=torch.float64)
tensor([4.9805, 0.2671, 4.7132], dtype=torch.float64)
Latent state
tensor([1.2409, 3.1327, 1.0102], grad_fn=<ExpandBackward>)
Observed
tensor([4.9809, 0.2674, 4.7132], dtype=torch.float64)
tensor([4.9809, 0.2674, 4.7132], dtype=torch.float64)
Latent state
tensor([1.2036, 3.1070, 1.0459], grad_fn=<ExpandBackward>)
Observed
tensor([4.9808, 0.2672, 4.7133], dtype=torch.float64)
tensor([4.9808, 0.2672, 4.7133], dtype=torch.float64)
Latent state
tensor([1.1787, 3.1067, 1.0674], grad_fn=<ExpandBackward>)
Observed
tensor([4.9808, 0.2673, 4.7132], dtype=torch.f

tensor([4.9806, 0.2677, 4.7127], dtype=torch.float64)
Latent state
tensor([1.6600, 3.8916, 1.1878], grad_fn=<ExpandBackward>)
Observed
tensor([4.9806, 0.2676, 4.7127], dtype=torch.float64)
tensor([4.9806, 0.2676, 4.7127], dtype=torch.float64)
Latent state
tensor([1.6551, 3.8892, 1.1832], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2676, 4.7127], dtype=torch.float64)
tensor([4.9805, 0.2676, 4.7127], dtype=torch.float64)
Latent state
tensor([1.6682, 3.9379, 1.1736], grad_fn=<ExpandBackward>)
Observed
tensor([4.9804, 0.2675, 4.7126], dtype=torch.float64)
tensor([4.9804, 0.2675, 4.7126], dtype=torch.float64)
Latent state
tensor([1.6806, 3.9134, 1.1483], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2676, 4.7126], dtype=torch.float64)
tensor([4.9805, 0.2676, 4.7126], dtype=torch.float64)
Latent state
tensor([1.6258, 3.7012, 1.0122], grad_fn=<ExpandBackward>)
Observed
tensor([4.9805, 0.2675, 4.7127], dtype=torch.float64)
tensor([4.9805, 0.2675, 4.7127], dtype=torch.float64)
L

Latent state
tensor([1.7990, 3.4153, 0.7926], grad_fn=<ExpandBackward>)
Observed
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
Latent state
tensor([1.7967, 3.3700, 0.7391], grad_fn=<ExpandBackward>)
Observed
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
Latent state
tensor([1.7791, 3.3553, 0.7149], grad_fn=<ExpandBackward>)
Observed
tensor([4.9801, 0.2686, 4.7113], dtype=torch.float64)
tensor([4.9801, 0.2686, 4.7113], dtype=torch.float64)
Latent state
tensor([1.8183, 3.4204, 0.7124], grad_fn=<ExpandBackward>)
Observed
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
tensor([4.9802, 0.2685, 4.7114], dtype=torch.float64)
Latent state
tensor([1.8012, 3.3768, 0.6819], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2684, 4.7114], dtype=torch.float64)
tensor([4.9800, 0.2684, 4.7114], dtype=torch.float64)
Latent state
tensor([1.7395, 3.2825, 0.7043], grad_fn=<

tensor([2.0696, 3.7514, 0.6334], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2688, 4.7109], dtype=torch.float64)
tensor([4.9800, 0.2688, 4.7109], dtype=torch.float64)
Latent state
tensor([2.0117, 3.6633, 0.6269], grad_fn=<ExpandBackward>)
Observed
tensor([4.9801, 0.2687, 4.7111], dtype=torch.float64)
tensor([4.9801, 0.2687, 4.7111], dtype=torch.float64)
Latent state
tensor([2.0149, 3.6264, 0.6703], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2687, 4.7110], dtype=torch.float64)
tensor([4.9800, 0.2687, 4.7110], dtype=torch.float64)
Latent state
tensor([1.9406, 3.5058, 0.6342], grad_fn=<ExpandBackward>)
Observed
tensor([4.9800, 0.2688, 4.7109], dtype=torch.float64)
tensor([4.9800, 0.2688, 4.7109], dtype=torch.float64)
Latent state
tensor([1.8509, 3.3658, 0.5638], grad_fn=<ExpandBackward>)
Observed
tensor([4.9802, 0.2689, 4.7110], dtype=torch.float64)
tensor([4.9802, 0.2689, 4.7110], dtype=torch.float64)
Latent state
tensor([1.8516, 3.3567, 0.6168], grad_fn=<ExpandBackwar

RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float